"""drop_dead_arena_columns

Revision ID: 061d3da02ea7
Revises: e590d3e8a9db
Create Date: 2026-04-16 20:06:02.757172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '061d3da02ea7'
down_revision: Union[str, Sequence[str], None] = 'e590d3e8a9db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_courses_is_arena_enabled'), table_name='public_courses')
    op.drop_column('public_courses', 'is_arena_enabled')
    op.drop_column('public_courses', 'difficulty')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('public_courses', sa.Column('difficulty', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('public_courses', sa.Column('is_arena_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_public_courses_is_arena_enabled'), 'public_courses', ['is_arena_enabled'], unique=False)
    # ### end Alembic commands ###
