"""add_acceptance_fields_to_arena_match

Revision ID: 0a3d539eecd3
Revises: a3d8815ec207
Create Date: 2026-04-12 23:20:26.863644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a3d539eecd3'
down_revision: Union[str, Sequence[str], None] = 'a3d8815ec207'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arena_match_players', sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('arena_matches', sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('arena_matches', 'deadline_at')
    op.drop_column('arena_match_players', 'accepted_at')
    # ### end Alembic commands ###
