"""add_question_type_to_arena_items

Revision ID: 43af1cac6fc6
Revises: 6a1f2d9c3b4e
Create Date: 2026-04-10 10:44:52.350172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43af1cac6fc6'
down_revision: Union[str, Sequence[str], None] = '6a1f2d9c3b4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_arena_events_event_id'), table_name='arena_events')
    op.create_foreign_key(None, 'arena_matches', 'arena_rooms', ['room_id'], ['id'], ondelete='SET NULL')
    
    # Safely add question_type with default for existing rows
    op.add_column('arena_question_pool_items', sa.Column('question_type', sa.String(), nullable=True))
    op.execute("UPDATE arena_question_pool_items SET question_type = 'MultipleChoice'")
    op.alter_column('arena_question_pool_items', 'question_type', nullable=False)
    
    op.alter_column('arena_question_pool_items', 'correct_option_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_arena_question_pool_items_question_type'), 'arena_question_pool_items', ['question_type'], unique=False)
    op.drop_index(op.f('ix_arena_rooms_latest_match_id'), table_name='arena_rooms')
    op.drop_index(op.f('ix_course_media_assets_course_source'), table_name='course_media_assets')
    op.create_index(op.f('ix_course_media_assets_id'), 'course_media_assets', ['id'], unique=False)
    op.drop_constraint(op.f('lesson_attempts_user_id_fkey'), 'lesson_attempts', type_='foreignkey')
    op.create_foreign_key(None, 'lesson_attempts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_lesson_failed_stages_difficulty'), table_name='lesson_failed_stages')
    op.create_index(op.f('ix_lesson_remedial_stages_stage_type'), 'lesson_remedial_stages', ['stage_type'], unique=False)
    op.create_index(op.f('ix_lesson_remedials_course_id'), 'lesson_remedials', ['course_id'], unique=False)
    op.drop_constraint(op.f('fk_lesson_remedials_lesson_session_id'), 'lesson_remedials', type_='foreignkey')
    op.create_foreign_key(None, 'lesson_remedials', 'lesson_sessions', ['lesson_session_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_lesson_session_stages_source_stage_uid'), 'lesson_session_stages', ['source_stage_uid'], unique=False)
    op.create_index(op.f('ix_lesson_stages_stage_type'), 'lesson_stages', ['stage_type'], unique=False)
    op.create_index(op.f('ix_lessons_course_id'), 'lessons', ['course_id'], unique=False)
    op.create_index(op.f('ix_user_ledger_events_event_type'), 'user_ledger_events', ['event_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_ledger_events_event_type'), table_name='user_ledger_events')
    op.drop_index(op.f('ix_lessons_course_id'), table_name='lessons')
    op.drop_index(op.f('ix_lesson_stages_stage_type'), table_name='lesson_stages')
    op.drop_index(op.f('ix_lesson_session_stages_source_stage_uid'), table_name='lesson_session_stages')
    op.drop_constraint(None, 'lesson_remedials', type_='foreignkey')
    op.create_foreign_key(op.f('fk_lesson_remedials_lesson_session_id'), 'lesson_remedials', 'lesson_sessions', ['lesson_session_id'], ['id'])
    op.drop_index(op.f('ix_lesson_remedials_course_id'), table_name='lesson_remedials')
    op.drop_index(op.f('ix_lesson_remedial_stages_stage_type'), table_name='lesson_remedial_stages')
    op.create_index(op.f('ix_lesson_failed_stages_difficulty'), 'lesson_failed_stages', ['difficulty'], unique=False)
    op.drop_constraint(None, 'lesson_attempts', type_='foreignkey')
    op.create_foreign_key(op.f('lesson_attempts_user_id_fkey'), 'lesson_attempts', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_course_media_assets_id'), table_name='course_media_assets')
    op.create_index(op.f('ix_course_media_assets_course_source'), 'course_media_assets', ['course_id', 'source_filename'], unique=False)
    op.create_index(op.f('ix_arena_rooms_latest_match_id'), 'arena_rooms', ['latest_match_id'], unique=False)
    op.drop_index(op.f('ix_arena_question_pool_items_question_type'), table_name='arena_question_pool_items')
    op.alter_column('arena_question_pool_items', 'correct_option_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('arena_question_pool_items', 'question_type')
    op.drop_constraint(None, 'arena_matches', type_='foreignkey')
    op.create_index(op.f('ix_arena_events_event_id'), 'arena_events', ['event_id'], unique=False)
    # ### end Alembic commands ###
