"""add source_course_id to public_courses

Revision ID: 7973be76bd90
Revises: 7fafb9ed78cd
Create Date: 2026-05-20 18:02:28.585583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7973be76bd90'
down_revision: Union[str, Sequence[str], None] = '7fafb9ed78cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('public_courses', sa.Column('source_course_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_public_courses_source_course_id'), 'public_courses', ['source_course_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_courses_source_course_id'), table_name='public_courses')
    op.drop_column('public_courses', 'source_course_id')
    # ### end Alembic commands ###
