"""add_question_pool_id_to_arena_models

Revision ID: e590d3e8a9db
Revises: 30b8a775256b
Create Date: 2026-04-16 19:52:27.604273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e590d3e8a9db'
down_revision: Union[str, Sequence[str], None] = '30b8a775256b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arena_matches', sa.Column('question_pool_id', sa.Integer(), nullable=True))
    op.create_index('ix_arena_matches_pool_status', 'arena_matches', ['question_pool_id', 'status'], unique=False)
    op.create_index(op.f('ix_arena_matches_question_pool_id'), 'arena_matches', ['question_pool_id'], unique=False)
    op.create_foreign_key(None, 'arena_matches', 'arena_question_pools', ['question_pool_id'], ['id'], ondelete='SET NULL')
    op.add_column('arena_queue_entries', sa.Column('question_pool_id', sa.Integer(), nullable=True))
    op.create_index('ix_arena_queue_entries_pool_status_created', 'arena_queue_entries', ['question_pool_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_arena_queue_entries_question_pool_id'), 'arena_queue_entries', ['question_pool_id'], unique=False)
    op.create_foreign_key(None, 'arena_queue_entries', 'arena_question_pools', ['question_pool_id'], ['id'], ondelete='SET NULL')
    op.add_column('arena_rooms', sa.Column('question_pool_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_arena_rooms_question_pool_id'), 'arena_rooms', ['question_pool_id'], unique=False)
    op.create_foreign_key(None, 'arena_rooms', 'arena_question_pools', ['question_pool_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'arena_rooms', type_='foreignkey')
    op.drop_index(op.f('ix_arena_rooms_question_pool_id'), table_name='arena_rooms')
    op.drop_column('arena_rooms', 'question_pool_id')
    op.drop_constraint(None, 'arena_queue_entries', type_='foreignkey')
    op.drop_index(op.f('ix_arena_queue_entries_question_pool_id'), table_name='arena_queue_entries')
    op.drop_index('ix_arena_queue_entries_pool_status_created', table_name='arena_queue_entries')
    op.drop_column('arena_queue_entries', 'question_pool_id')
    op.drop_constraint(None, 'arena_matches', type_='foreignkey')
    op.drop_index(op.f('ix_arena_matches_question_pool_id'), table_name='arena_matches')
    op.drop_index('ix_arena_matches_pool_status', table_name='arena_matches')
    op.drop_column('arena_matches', 'question_pool_id')
    # ### end Alembic commands ###
